# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mirivera <mirivera@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/24 10:31:43 by mirivera          #+#    #+#              #
#    Updated: 2020/01/24 10:31:45 by mirivera         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine

RUN apk update && apk add vim 

# run container with:
# docker run -itd --name alpine my_alpine sh && docker exec -it alpine sh